local MSG = {}

MSG.VERSION 				= 1

MSG.RESULT_OK				= 1
MSG.RESULT_PROTOCOL_ERROR	= 2
MSG.RESULT_MYSQL_ERRORR		= 3

MSG.HEARTBEAT_SC 			= 10000
MSG.ROLE_LOGIN_REQUEST_CS	= 10001
MSG.ROLE_LOGIN_RESPONSE_SC	= 10002

return MSG
